/**
 * Static SA listing data used as a front-end fallback when the API
 * is unavailable (e.g. during UI-only development / demo mode).
 *
 * Import and use in place of API calls:
 *   import { DEMO_LISTINGS } from '../utils/seedData'
 */

export const DEMO_LISTINGS = [
  {
    _id: 'demo-1',
    title: 'Luxury Sea-View Villa – Clifton',
    description:
      'Perched above the iconic Clifton beaches, this stunning villa offers breathtaking Atlantic Ocean views. White-washed walls, a private infinity pool, and direct beach access make this the ultimate Cape Town escape.',
    location: 'Clifton, Cape Town',
    pricePerNight: 8500,
    propertyType: 'Villa',
    category: 'Beachfront',
    maxGuests: 8,
    bedrooms: 4,
    bathrooms: 3,
    amenities: ['WiFi', 'Pool', 'Kitchen', 'Air conditioning', 'Parking', 'TV'],
    photos: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop',
    ],
    avgRating: 4.9,
    reviewCount: 38,
    weeklyDiscount: 10,
    cleaningFee: 850,
    serviceFee: 500,
    occupancyTaxes: 250,
    host: { name: 'Banele Dlamini', bio: 'South African property host.' },
  },
  {
    _id: 'demo-2',
    title: 'Cosy Garden Cottage – Stellenbosch Wine Country',
    description:
      'Nestled in the heart of the Cape Winelands, this charming stone cottage sits on a working wine estate. Wake up to mountain views and enjoy complimentary wine tastings.',
    location: 'Stellenbosch, Western Cape',
    pricePerNight: 2200,
    propertyType: 'Cottage',
    category: 'Countryside',
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['WiFi', 'Kitchen', 'Heating', 'Parking', 'TV'],
    photos: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&auto=format&fit=crop',
    ],
    avgRating: 4.8,
    reviewCount: 22,
    weeklyDiscount: 15,
    cleaningFee: 300,
    serviceFee: 200,
    occupancyTaxes: 100,
    host: { name: 'Banele Dlamini', bio: 'South African property host.' },
  },
  {
    _id: 'demo-3',
    title: 'Modern Sandton Apartment – Heart of Johannesburg',
    description:
      'Sleek, contemporary apartment in the prestigious Sandton CBD. Floor-to-ceiling windows showcase the city skyline. Walking distance to Sandton City Mall and the Gautrain station.',
    location: 'Sandton, Johannesburg',
    pricePerNight: 1800,
    propertyType: 'Apartment',
    category: 'Amazing views',
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ['WiFi', 'TV', 'Kitchen', 'Air conditioning', 'Gym', 'Parking'],
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop',
    ],
    avgRating: 4.6,
    reviewCount: 51,
    weeklyDiscount: 8,
    cleaningFee: 400,
    serviceFee: 300,
    occupancyTaxes: 150,
    host: { name: 'Banele Dlamini', bio: 'South African property host.' },
  },
  {
    _id: 'demo-4',
    title: 'Beachfront Bungalow – Umhlanga Rocks',
    description:
      'Step directly onto the golden sands of Umhlanga from this bright beachfront bungalow. Feel the warm Indian Ocean breeze and watch dolphins from the deck.',
    location: 'Umhlanga, KwaZulu-Natal',
    pricePerNight: 3200,
    propertyType: 'House',
    category: 'Beachfront',
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ['WiFi', 'Air conditioning', 'Kitchen', 'TV', 'Parking'],
    photos: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&auto=format&fit=crop',
    ],
    avgRating: 4.7,
    reviewCount: 29,
    weeklyDiscount: 12,
    cleaningFee: 500,
    serviceFee: 350,
    occupancyTaxes: 200,
    host: { name: 'Banele Dlamini', bio: 'South African property host.' },
  },
  {
    _id: 'demo-5',
    title: "Drakensberg Mountain Cabin – Hiker's Paradise",
    description:
      "Escape to this rustic log cabin nestled in the foothills of the uKhahlamba Drakensberg. A wood-burning fireplace keeps you warm on cool mountain nights.",
    location: 'Drakensberg, KwaZulu-Natal',
    pricePerNight: 1500,
    propertyType: 'Cabin',
    category: 'Cabins',
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['WiFi', 'Heating', 'Kitchen', 'Parking'],
    photos: [
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&auto=format&fit=crop',
    ],
    avgRating: 4.9,
    reviewCount: 17,
    weeklyDiscount: 20,
    cleaningFee: 250,
    serviceFee: 150,
    occupancyTaxes: 80,
    host: { name: 'Banele Dlamini', bio: 'South African property host.' },
  },
  {
    _id: 'demo-6',
    title: 'Luxury Game Lodge – Waterberg Bushveld',
    description:
      'Experience the authentic African bush in this exclusive private game lodge. Fall asleep to the sounds of the wild and wake up for sunrise game drives.',
    location: 'Waterberg, Limpopo',
    pricePerNight: 5500,
    propertyType: 'Villa',
    category: 'Luxury',
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ['WiFi', 'Pool', 'Air conditioning', 'Kitchen', 'Parking'],
    photos: [
      'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&auto=format&fit=crop',
    ],
    avgRating: 5.0,
    reviewCount: 11,
    weeklyDiscount: 5,
    cleaningFee: 800,
    serviceFee: 600,
    occupancyTaxes: 300,
    host: { name: 'Banele Dlamini', bio: 'South African property host.' },
  },
  {
    _id: 'demo-7',
    title: 'Knysna Lagoon Houseboat',
    description:
      'A beautifully converted houseboat moored on the tranquil Knysna Lagoon. The iconic Knysna Heads are visible from the upper sun deck.',
    location: 'Knysna, Garden Route',
    pricePerNight: 2800,
    propertyType: 'Loft',
    category: 'Amazing views',
    maxGuests: 4,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['WiFi', 'Kitchen', 'TV', 'Air conditioning'],
    photos: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&auto=format&fit=crop',
    ],
    avgRating: 4.8,
    reviewCount: 24,
    weeklyDiscount: 10,
    cleaningFee: 450,
    serviceFee: 280,
    occupancyTaxes: 140,
    host: { name: 'Banele Dlamini', bio: 'South African property host.' },
  },
  {
    _id: 'demo-8',
    title: 'Bo-Kaap Heritage Apartment – Cape Town',
    description:
      "Live like a local in one of Cape Town's most vibrant and colourful neighbourhoods. This restored apartment features original Cape Malay architecture.",
    location: 'Bo-Kaap, Cape Town',
    pricePerNight: 1600,
    propertyType: 'Apartment',
    category: 'Countryside',
    maxGuests: 3,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['WiFi', 'Kitchen', 'TV', 'Air conditioning'],
    photos: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&auto=format&fit=crop',
    ],
    avgRating: 4.7,
    reviewCount: 33,
    weeklyDiscount: 10,
    cleaningFee: 300,
    serviceFee: 200,
    occupancyTaxes: 100,
    host: { name: 'Banele Dlamini', bio: 'South African property host.' },
  },
  {
    _id: 'demo-9',
    title: 'Franschhoek Farm Stay – Winelands Retreat',
    description:
      "A spacious farmhouse set on a working lavender farm in the Franschhoek valley. Enjoy farm-fresh breakfasts and easy access to the village's world-class restaurants.",
    location: 'Franschhoek, Western Cape',
    pricePerNight: 3400,
    propertyType: 'Farm',
    category: 'Farms',
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ['WiFi', 'Kitchen', 'Heating', 'Parking', 'Pet-friendly'],
    photos: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=800&auto=format&fit=crop',
    ],
    avgRating: 4.9,
    reviewCount: 19,
    weeklyDiscount: 15,
    cleaningFee: 550,
    serviceFee: 400,
    occupancyTaxes: 200,
    host: { name: 'Banele Dlamini', bio: 'South African property host.' },
  },
  {
    _id: 'demo-10',
    title: 'Panoramic Studio – Signal Hill, Cape Town',
    description:
      'A stylish, compact studio with sweeping panoramic views over Cape Town, the harbour and Table Mountain. Features a private roof terrace perfect for sundowners.',
    location: 'Green Point, Cape Town',
    pricePerNight: 1200,
    propertyType: 'Studio',
    category: 'Amazing views',
    maxGuests: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['WiFi', 'TV', 'Kitchen', 'Air conditioning', 'Dedicated workspace'],
    photos: [
      'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&auto=format&fit=crop',
    ],
    avgRating: 4.6,
    reviewCount: 42,
    weeklyDiscount: 10,
    cleaningFee: 200,
    serviceFee: 150,
    occupancyTaxes: 75,
    host: { name: 'Banele Dlamini', bio: 'South African property host.' },
  },
  {
    _id: 'demo-11',
    title: 'Plettenberg Bay Beach House',
    description:
      "A large, airy beach house just metres from the famous Robberg Beach. Spacious open-plan living and a wrap-around deck for whale watching.",
    location: 'Plettenberg Bay, Garden Route',
    pricePerNight: 4200,
    propertyType: 'House',
    category: 'Beachfront',
    maxGuests: 10,
    bedrooms: 5,
    bathrooms: 3,
    amenities: ['WiFi', 'Kitchen', 'Air conditioning', 'Parking', 'TV', 'Washing machine', 'Pet-friendly'],
    photos: [
      'https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop',
    ],
    avgRating: 4.8,
    reviewCount: 27,
    weeklyDiscount: 15,
    cleaningFee: 700,
    serviceFee: 450,
    occupancyTaxes: 220,
    host: { name: 'Banele Dlamini', bio: 'South African property host.' },
  },
  {
    _id: 'demo-12',
    title: 'Luxury Penthouse – V&A Waterfront, Cape Town',
    description:
      "The pinnacle of Cape Town luxury. This penthouse apartment sits directly on the V&A Waterfront with unobstructed views of Table Mountain, Robben Island, and the Atlantic.",
    location: 'V&A Waterfront, Cape Town',
    pricePerNight: 12000,
    propertyType: 'Apartment',
    category: 'Luxury',
    maxGuests: 6,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ['WiFi', 'Pool', 'Hot tub', 'TV', 'Kitchen', 'Air conditioning', 'Gym', 'Parking'],
    photos: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&auto=format&fit=crop',
    ],
    avgRating: 5.0,
    reviewCount: 9,
    weeklyDiscount: 8,
    cleaningFee: 1500,
    serviceFee: 900,
    occupancyTaxes: 500,
    host: { name: 'Banele Dlamini', bio: 'South African property host.' },
  },
]

/**
 * Filter demo listings client-side (mirrors API query params).
 */
export function filterDemoListings({ location, category, minPrice, maxPrice, guests } = {}) {
  return DEMO_LISTINGS.filter((l) => {
    if (location && !l.location.toLowerCase().includes(location.toLowerCase())) return false
    if (category && l.category !== category) return false
    if (minPrice && l.pricePerNight < Number(minPrice)) return false
    if (maxPrice && l.pricePerNight > Number(maxPrice)) return false
    if (guests && l.maxGuests < Number(guests)) return false
    return true
  })
}
